### ISSUE TITLE
Phase 1: present materials to your review team. 

### ISSUE THREAD

**Issue by elifleaf** [ertekin-research-group/papertest#8]
# Present materials to your review team. 

Arrange to meet with your review team. Plan for this process to take about 2 hours.  Reserve a room with projector and use it when showing your materials. 

The review team will work with the main author(s) until everyone agrees that the principal elements of the one sentence summary, abstract, and figures are in place. 

The paper author(s) should be able to clearly explain all aspects of their manuscript to the review team. 

The review team has an important role to fulfill and should be critical and constructive. Please do not be lazy about working with the paper authors -- this process will only work if everyone commits. Ask for clarifications if you think something is not clear. Be helpful with your comments, but do not let your authors off the hook if you feel that elements/requirements have not been fulfilled. This does not help anyone in the long run. Think about how you would like to receive feedback if you were the author, and try to give your feedback in that manner. 

# Task Breakdown 

## Present your one sentence summary of your paper theme and bullet point list of supporting evidence. 

Authors: show a slide with your one sentence summary and bullet point list of supporting information. 

Review Team: assess the following:
- [ ] The one sentence summary statement is clear and concise, and conveys a complete idea that will serve as the principal theme of this manuscript. 
- [ ] The bullet-point list of supporting evidence ties clearly back to the main theme. 
- [ ] There is enough supporting evidence to make the argument. 

## Present your abstract.

Authors: show a slide with your abstract to your review team and let your review team read it. 

Review Team:  assess the following: 
- [ ] The abstract presents a concise summary, including introductory sentences, a statement of the main theme, sentences describing the results, and concludes with a general statement about why it matters.  Try to identify each required element. 
- [ ] The elements above are presented at the right amount of detail (sufficient, but not excessive)
- [ ] The abstract is written with clear english and is free of grammatical and/or spelling errors. 

## Present your figure set. 

Authors: show each figure one at a time to your review team, and carefully explain each Figure.  In addition to the figure itself, the "To learn" statement and the caption should be included on each slide.  

Review Team: 
At this point, just by looking at the Figures alone, you should be able to get a good understanding of the flow and logic development of the paper.  

For each figure, address the following related to content:
- [ ] Do the panels of the Figure support the "To learn:" statement? 
- [ ] Does the caption make clear what you are looking at? 

For each figure, address the following related to formatting: 
- [ ] The figure has been saved in an appropriate format. 
- [ ] There is no excess white space anywhere.
- [ ] The font and font size is appropriate. 
- [ ] Everything that needs labeling has been properly labeled. 
- [ ] Units are included wherever they should be included. 

For the whole figure set
- [ ] Does the figure set as a whole support the main theme of the paper? 
- [ ] As the figures were presented to you one by one, did the author lay out a clear argument in support of their main theme? 
- [ ] Does the order of the Figures make sense, in order to make the strongest argument? 
- [ ] Are there any missing steps in the logic flow of the paper? Are there any gaps that need to be addressed?
